-- Vast Nation: functional account settings, store settings and live admin notifications.

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  theme text not null default 'dark' check (theme in ('light','dark','system')),
  order_updates boolean not null default true,
  payment_updates boolean not null default true,
  shipping_updates boolean not null default true,
  product_alerts boolean not null default true,
  newsletter boolean not null default true,
  promotions boolean not null default true,
  updated_at timestamptz not null default now()
);
alter table public.user_settings enable row level security;
drop policy if exists "user_settings_select_own" on public.user_settings;
create policy "user_settings_select_own" on public.user_settings for select to authenticated using (auth.uid() = user_id);
drop policy if exists "user_settings_insert_own" on public.user_settings;
create policy "user_settings_insert_own" on public.user_settings for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "user_settings_update_own" on public.user_settings;
create policy "user_settings_update_own" on public.user_settings for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop trigger if exists user_settings_updated_at on public.user_settings;
create or replace function public.set_user_settings_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger user_settings_updated_at before update on public.user_settings for each row execute function public.set_user_settings_updated_at();

create table if not exists public.store_settings (
  id uuid primary key default gen_random_uuid(),
  store_name text not null default 'Vast Nation',
  store_email text not null default '',
  store_phone text not null default '',
  store_address text not null default '',
  currency text not null default 'NGN',
  free_shipping_threshold numeric(12,2) not null default 100000,
  standard_shipping_fee numeric(12,2) not null default 2500,
  express_shipping_fee numeric(12,2) not null default 5000,
  tax_rate numeric(6,3) not null default 0,
  maintenance_mode boolean not null default false,
  notify_new_order boolean not null default true,
  notify_payment boolean not null default true,
  notify_low_stock boolean not null default true,
  notify_new_review boolean not null default true,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.store_settings enable row level security;
drop policy if exists "store_settings_public_read" on public.store_settings;
create policy "store_settings_public_read" on public.store_settings for select to anon, authenticated using (true);
drop policy if exists "store_settings_admin_insert" on public.store_settings;
create policy "store_settings_admin_insert" on public.store_settings for insert to authenticated with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
drop policy if exists "store_settings_admin_update" on public.store_settings;
create policy "store_settings_admin_update" on public.store_settings for update to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

insert into public.store_settings (id) select gen_random_uuid() where not exists (select 1 from public.store_settings);

create table if not exists public.admin_notifications (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  title text not null,
  message text not null,
  entity_id uuid,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.admin_notifications enable row level security;
drop policy if exists "admin_notifications_admin_read" on public.admin_notifications;
create policy "admin_notifications_admin_read" on public.admin_notifications for select to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
drop policy if exists "admin_notifications_admin_update" on public.admin_notifications;
create policy "admin_notifications_admin_update" on public.admin_notifications for update to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

-- Trigger functions run with definer privileges so an event generated by checkout/webhooks
-- can create an admin notification without exposing an insert policy to customers.
create or replace function public.create_admin_notification(
  p_type text,
  p_title text,
  p_message text,
  p_entity_id uuid default null
) returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.admin_notifications(type, title, message, entity_id)
  values (p_type, p_title, p_message, p_entity_id);
end;
$$;

create or replace function public.notify_vast_nation_order() returns trigger language plpgsql security definer set search_path = public as $$
declare s public.store_settings%rowtype; customer_name text;
begin
  select * into s from public.store_settings order by updated_at desc limit 1;
  if tg_op = 'INSERT' and coalesce(s.notify_new_order, true) then
    select coalesce(nullif(trim(p.full_name), ''), nullif(trim(p.email), ''), 'A customer') into customer_name from public.profiles p where p.id = new.user_id;
    perform public.create_admin_notification('new_order', 'New order received', customer_name || ' placed order ' || coalesce(new.order_number, new.id::text) || ' for ₦' || to_char(coalesce(new.total,0), 'FM999,999,990.00'), new.id);
  elsif tg_op = 'UPDATE' and old.payment_status is distinct from new.payment_status and new.payment_status = 'paid' and coalesce(s.notify_payment, true) then
    select coalesce(nullif(trim(p.full_name), ''), nullif(trim(p.email), ''), 'A customer') into customer_name from public.profiles p where p.id = new.user_id;
    perform public.create_admin_notification('payment', 'Payment confirmed', customer_name || ' paid ₦' || to_char(coalesce(new.total,0), 'FM999,999,990.00') || ' for order ' || coalesce(new.order_number, new.id::text), new.id);
  end if;
  return new;
end;
$$;
drop trigger if exists orders_admin_notification on public.orders;
create trigger orders_admin_notification after insert or update of payment_status on public.orders for each row execute function public.notify_vast_nation_order();

create or replace function public.notify_vast_nation_review() returns trigger language plpgsql security definer set search_path = public as $$
declare s public.store_settings%rowtype; customer_name text; product_name text;
begin
  select * into s from public.store_settings order by updated_at desc limit 1;
  if coalesce(s.notify_new_review, true) then
    select coalesce(nullif(trim(p.full_name), ''), nullif(trim(p.email), ''), 'A customer') into customer_name from public.profiles p where p.id = new.user_id;
    select name into product_name from public.products where id = new.product_id;
    perform public.create_admin_notification('review', 'New product review', customer_name || ' reviewed ' || coalesce(product_name, 'a product') || ' (' || new.rating || '/5).', new.id);
  end if;
  return new;
end;
$$;
drop trigger if exists reviews_admin_notification on public.reviews;
create trigger reviews_admin_notification after insert on public.reviews for each row execute function public.notify_vast_nation_review();

create or replace function public.notify_vast_nation_low_stock() returns trigger language plpgsql security definer set search_path = public as $$
declare s public.store_settings%rowtype;
begin
  if new.stock <= 5 and (old.stock > 5 or old.stock is null) then
    select * into s from public.store_settings order by updated_at desc limit 1;
    if coalesce(s.notify_low_stock, true) then
      perform public.create_admin_notification('low_stock', 'Low stock alert', new.name || ' has only ' || new.stock || ' item(s) remaining.', new.id);
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists products_low_stock_notification on public.products;
create trigger products_low_stock_notification after update of stock on public.products for each row execute function public.notify_vast_nation_low_stock();

-- Make live admin notifications available through Supabase Realtime.
do $$ begin
  alter publication supabase_realtime add table public.admin_notifications;
exception when duplicate_object then null; end $$;
