[functions.paystack-initialize]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-initialize/deno.json"
entrypoint = "./functions/paystack-initialize/index.ts"

[functions.paystack-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/paystack-webhook/deno.json"
entrypoint = "./functions/paystack-webhook/index.ts"

[functions.create-admin]
enabled = true
verify_jwt = true
import_map = "./functions/create-admin/deno.json"
entrypoint = "./functions/create-admin/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = true
import_map = "./functions/delete-account/deno.json"
entrypoint = "./functions/delete-account/index.ts"
