import { useEffect, useRef, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { ArrowLeft, Bell, Camera, LogOut, Save, Shield, Store, Trash2, UserPlus, Lock } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { formatNaira } from '../utils/helpers';
import { uploadProfileImage } from '../services/storage';

type StoreSettings = {
  id: string; store_name: string; store_email: string; store_phone: string; store_address: string;
  currency: string; free_shipping_threshold: number; standard_shipping_fee: number; express_shipping_fee: number;
  tax_rate: number; maintenance_mode: boolean; notify_new_order: boolean; notify_payment: boolean; notify_low_stock: boolean; notify_new_review: boolean;
};
const defaults: StoreSettings = { id: '', store_name: 'Vast Nation', store_email: '', store_phone: '', store_address: '', currency: 'NGN', free_shipping_threshold: 100000, standard_shipping_fee: 2500, express_shipping_fee: 5000, tax_rate: 0, maintenance_mode: false, notify_new_order: true, notify_payment: true, notify_low_stock: true, notify_new_review: true };

export default function AdminSettings() {
  const { user, profile, loading: authLoading, signOut, refreshProfile, changePassword, deleteAccount } = useAuth();
  const { toast } = useToast();
  const [settings, setSettings] = useState<StoreSettings>(defaults);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [fullName, setFullName] = useState(''); const [phone, setPhone] = useState('');
  const [uploadingAvatar, setUploadingAvatar] = useState(false); const avatarRef = useRef<HTMLInputElement>(null);
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [changingPassword, setChangingPassword] = useState(false);
  const [newAdminEmail, setNewAdminEmail] = useState(''); const [newAdminPassword, setNewAdminPassword] = useState(''); const [newAdminName, setNewAdminName] = useState(''); const [addingAdmin, setAddingAdmin] = useState(false);

  useEffect(() => { if (!user || profile?.role !== 'admin') return; setFullName(profile.full_name ?? ''); setPhone(profile.phone ?? ''); (async () => { const { data, error } = await supabase.from('store_settings').select('*').order('updated_at', { ascending: false }).limit(1).maybeSingle(); if (error) toast('Failed to load store settings: ' + error.message, 'error'); else if (data) setSettings(data as StoreSettings); setLoading(false); })(); }, [user, profile, toast]);
  const update = <K extends keyof StoreSettings>(key: K, value: StoreSettings[K]) => setSettings(s => ({ ...s, [key]: value }));
  const save = async () => { if (!user) return; setSaving(true); try { const { data, error } = await supabase.from('store_settings').upsert({ ...settings, id: settings.id || undefined, updated_by: user.id }, { onConflict: 'id' }).select().single(); if (error) throw error; setSettings(data as StoreSettings); toast('Store settings saved successfully', 'success'); } catch (e) { toast(e instanceof Error ? e.message : 'Failed to save settings', 'error'); } finally { setSaving(false); } };
  const saveAdminProfile = async () => { if (!user) return; try { const { error } = await supabase.from('profiles').update({ full_name: fullName.trim(), phone: phone.trim() }).eq('id', user.id); if (error) throw error; await refreshProfile(); toast('Admin profile updated', 'success'); } catch (e) { toast(e instanceof Error ? e.message : 'Failed to update profile', 'error'); } };
  const uploadAvatar = async (file?: File) => { if (!file || !user) return; setUploadingAvatar(true); try { const url = await uploadProfileImage(file, user.id); const { error } = await supabase.from('profiles').update({ avatar_url: url }).eq('id', user.id); if (error) throw error; await refreshProfile(); toast('Admin profile image updated', 'success'); } catch (e) { toast(e instanceof Error ? e.message : 'Failed to upload image', 'error'); } finally { setUploadingAvatar(false); } };
  const handlePassword = async () => { if (newPassword.length < 8) return toast('New password must be at least 8 characters.', 'error'); if (newPassword !== confirmPassword) return toast('Passwords do not match.', 'error'); setChangingPassword(true); try { await changePassword(currentPassword, newPassword); setCurrentPassword(''); setNewPassword(''); setConfirmPassword(''); toast('Password changed successfully', 'success'); } catch (e) { toast(e instanceof Error ? e.message : 'Failed to change password', 'error'); } finally { setChangingPassword(false); } };
  const addAdmin = async () => { if (!newAdminEmail || newAdminPassword.length < 8 || !newAdminName.trim()) return toast('Enter admin name, email and a password of at least 8 characters.', 'error'); setAddingAdmin(true); try { const { data: session } = await supabase.auth.getSession(); const { error } = await supabase.functions.invoke('create-admin', { headers: { Authorization: `Bearer ${session.session?.access_token ?? ''}` }, body: { email: newAdminEmail.trim(), password: newAdminPassword, full_name: newAdminName.trim() } }); if (error) throw error; setNewAdminEmail(''); setNewAdminPassword(''); setNewAdminName(''); toast('New admin account created successfully', 'success'); } catch (e) { toast(e instanceof Error ? e.message : 'Failed to create admin', 'error'); } finally { setAddingAdmin(false); } };
  const removeAccount = async () => { if (!window.confirm('Delete your admin account permanently? This cannot be undone.')) return; try { await deleteAccount(); window.location.href = '/'; } catch (e) { toast(e instanceof Error ? e.message : 'Failed to delete account', 'error'); } };
  const logout = async () => { await signOut(); window.location.href = '/login'; };

  if (authLoading || loading) return <div className="min-h-screen flex items-center justify-center text-ink-400">Loading settings…</div>;
  if (!user) return <Navigate to="/login" replace />; if (profile?.role !== 'admin') return <Navigate to="/dashboard" replace />;

  return <div className="section-padding py-10 min-h-screen"><div className="max-w-5xl mx-auto">
    <div className="flex items-center justify-between gap-4 mb-8"><div><Link to="/admin" className="text-xs text-ink-400 hover:text-gold-400 flex items-center gap-1 mb-3"><ArrowLeft className="w-3.5 h-3.5" /> Back to Admin</Link><h1 className="font-display text-3xl font-bold text-white">Admin Settings</h1><p className="text-sm text-ink-400 mt-1">Manage your admin account and the Vast Nation store.</p></div><button onClick={() => void save()} disabled={saving} className="btn-gold px-5 py-3 rounded-lg flex items-center gap-2 disabled:opacity-50"><Save className="w-4 h-4" />{saving ? 'Saving…' : 'Save Store Settings'}</button></div>

    <section className="glass rounded-2xl p-6 mb-6"><div className="flex items-center gap-3 mb-5"><Shield className="text-gold-400" /><div><h2 className="font-semibold text-white">Admin Profile</h2><p className="text-xs text-ink-400">Your administrator identity and profile photo.</p></div></div><div className="flex items-center gap-5 mb-6"><div className="w-24 h-24 rounded-full overflow-hidden border border-gold-400/30 bg-gold-400/10 flex items-center justify-center text-gold-400 text-2xl font-bold">{profile.avatar_url ? <img src={profile.avatar_url} alt="Admin profile" className="w-full h-full object-cover" /> : (profile.full_name?.[0] ?? user.email[0] ?? 'A').toUpperCase()}</div><div><button type="button" onClick={() => avatarRef.current?.click()} disabled={uploadingAvatar} className="btn-gold rounded-lg px-4 py-2 text-xs flex items-center gap-2"><Camera className="w-4 h-4" />{uploadingAvatar ? 'Uploading…' : 'Upload profile image'}</button><input ref={avatarRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" onChange={e => void uploadAvatar(e.target.files?.[0])}/><p className="text-xs text-ink-500 mt-2">Maximum 5MB.</p></div></div><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm text-ink-300">Full name<input className="input-field mt-2" value={fullName} onChange={e => setFullName(e.target.value)} /></label><label className="text-sm text-ink-300">Email<input className="input-field mt-2 opacity-60" value={user.email} disabled /></label><label className="text-sm text-ink-300">Phone<input className="input-field mt-2" value={phone} onChange={e => setPhone(e.target.value)} /></label></div><button type="button" onClick={() => void saveAdminProfile()} className="mt-4 px-4 py-2 rounded-lg bg-white/10 text-white text-sm hover:bg-white/15">Save Admin Profile</button></section>

    <section className="glass rounded-2xl p-6 mb-6"><div className="flex items-center gap-3 mb-5"><Store className="text-gold-400" /><div><h2 className="font-semibold text-white">Store Information</h2><p className="text-xs text-ink-400">Customer-facing store configuration.</p></div></div><div className="grid sm:grid-cols-2 gap-4">{([['store_name','Store name'],['store_email','Store email'],['store_phone','Store phone'],['currency','Currency']] as const).map(([key,label]) => <label key={key} className="text-sm text-ink-300">{label}<input className="input-field mt-2" value={settings[key] as string} onChange={e => update(key,e.target.value)} /></label>)}<label className="sm:col-span-2 text-sm text-ink-300">Store address<textarea className="input-field mt-2 min-h-24" value={settings.store_address} onChange={e => update('store_address',e.target.value)} /></label></div></section>

    <section className="glass rounded-2xl p-6 mb-6"><h2 className="font-semibold text-white mb-5">Shipping & Tax</h2><div className="grid sm:grid-cols-2 gap-4">{([['free_shipping_threshold','Free shipping threshold'],['standard_shipping_fee','Standard shipping fee'],['express_shipping_fee','Express shipping fee'],['tax_rate','Tax rate (%)']] as const).map(([key,label]) => <label key={key} className="text-sm text-ink-300">{label}<input type="number" min="0" className="input-field mt-2" value={settings[key] as number} onChange={e => update(key,Number(e.target.value))}/><span className="text-[11px] text-ink-500 mt-1 block">{key === 'tax_rate' ? `${settings[key]}%` : formatNaira(Number(settings[key]))}</span></label>)}</div></section>

    <section className="glass rounded-2xl p-6 mb-6"><div className="flex items-center gap-3 mb-5"><Bell className="text-gold-400"/><div><h2 className="font-semibold text-white">Admin Notifications</h2><p className="text-xs text-ink-400">These settings control live database notification events.</p></div></div>{([['notify_new_order','New orders','Notify when a new order is created.'],['notify_payment','Successful payments','Notify when a Paystack payment is confirmed.'],['notify_low_stock','Low stock','Notify when stock falls to five or fewer.'],['notify_new_review','New reviews','Notify when a customer submits a review.']] as const).map(([key,title,desc]) => <label key={key} className="flex items-center justify-between gap-4 py-4 border-b border-white/5 cursor-pointer"><div><div className="text-sm text-white font-medium">{title}</div><div className="text-xs text-ink-500 mt-1">{desc}</div></div><input type="checkbox" className="accent-gold-400 w-5 h-5" checked={settings[key]} onChange={e => update(key,e.target.checked)}/></label>)}<label className="flex items-center justify-between gap-4 py-4 cursor-pointer"><div><div className="text-sm text-white font-medium">Maintenance mode</div><div className="text-xs text-ink-500 mt-1">Keep this off unless you intentionally want to disable normal storefront access.</div></div><input type="checkbox" className="accent-gold-400 w-5 h-5" checked={settings.maintenance_mode} onChange={e => update('maintenance_mode',e.target.checked)}/></label></section>

    <section className="glass rounded-2xl p-6 mb-6"><div className="flex items-center gap-3 mb-5"><UserPlus className="text-gold-400"/><div><h2 className="font-semibold text-white">Add New Admin</h2><p className="text-xs text-ink-400">Create another administrator without exposing service-role credentials.</p></div></div><div className="grid sm:grid-cols-3 gap-4"><input className="input-field" placeholder="Full name" value={newAdminName} onChange={e=>setNewAdminName(e.target.value)}/><input className="input-field" type="email" placeholder="Email" value={newAdminEmail} onChange={e=>setNewAdminEmail(e.target.value)}/><input className="input-field" type="password" placeholder="Temporary password (8+)" value={newAdminPassword} onChange={e=>setNewAdminPassword(e.target.value)}/></div><button type="button" onClick={() => void addAdmin()} disabled={addingAdmin} className="btn-gold mt-4 rounded-lg px-4 py-2 text-sm disabled:opacity-50">{addingAdmin ? 'Creating…' : 'Create Admin Account'}</button></section>

    <section className="glass rounded-2xl p-6 mb-6"><div className="flex items-center gap-3 mb-5"><Lock className="text-gold-400"/><div><h2 className="font-semibold text-white">Change Password</h2><p className="text-xs text-ink-400">Your current password is verified before the new password is saved.</p></div></div><div className="grid gap-3 max-w-xl"><input className="input-field" type="password" placeholder="Current password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/><input className="input-field" type="password" placeholder="New password (8+)" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><input className="input-field" type="password" placeholder="Confirm new password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></div><button type="button" onClick={() => void handlePassword()} disabled={changingPassword} className="btn-gold mt-4 rounded-lg px-4 py-2 text-sm disabled:opacity-50">{changingPassword ? 'Changing…' : 'Change Password'}</button></section>

    <section className="glass rounded-2xl p-6 border border-red-500/20"><h2 className="font-semibold text-white mb-4">Account Actions</h2><div className="flex flex-wrap gap-4"><button type="button" onClick={() => void logout()} className="px-4 py-2 rounded-lg bg-white/10 text-white text-sm flex items-center gap-2"><LogOut className="w-4 h-4"/>Log out</button><button type="button" onClick={() => void removeAccount()} className="px-4 py-2 rounded-lg bg-red-500/10 text-red-400 text-sm flex items-center gap-2"><Trash2 className="w-4 h-4"/>Delete my admin account</button></div><p className="text-xs text-ink-500 mt-3">Deleting your account removes your authentication account and profile permanently.</p></section>
  </div></div>;
}
